module.exports = {
  _firstHomePage: "----------------------------------------------",
  carouselImagesCss: ".carousel-item.active img",
  carouselPositionIndicatorsCss: "[data-target='#carouselExampleIndicators']",
  laptopsCategoryCss: "[onclick=\"byCat('notebook')\"]",
  linkAboutusCss: "[data-target='#videoModal']",
  linkCarouselLeftArrowClass: ".carousel-control-prev",
  linkCarouselRightArrowClass: ".carousel-control-next",
  linkCartId: "#cartur",
  linkContactCss: "[data-target='#exampleModal']",
  linkHomeCss: "li a[href='index.html']",
  linkLoginId: "#login2",
  linkLogoId: "#nava",
  linkLogoutId: "#logout2",
  linkSignupId: "#signin2",
  linkUserNameId: "#nameofuser",
  monitorsCategoryCss: "[onclick=\"byCat('monitor')\"]",
  nextButtonId: "#next2",
  phonesCategoryCss: "[onclick=\"byCat('phone')\"]",
  previousButtonId: "#prev2",
  productDescriptionCss: ".card p",
  productImagesCss: ".card > a",
  productPricesCss: ".card div h5",
  productTitlesClass: ".hrefch",
  _lastHomePage: "----------------------------------------------",
  classProductTitle: ".name",
  classProductPrice: ".price-container",
  idPriceProductDescription: "#more-information p",
  classProductImage: ".product-image",
  classAddToCartButton: ".btn-success",
  cssCardImages: ".card-img-top.img-fluid",
  cssCardTitles: ".card-title .hrefch",
  cssCardPrices: ".card-block h5",
  cssCardDescriptions: ".card-text",
};
