module.exports = {
  _firstHomePage: "----------------------------------------------",
  carouselImagesCss: ".carousel-item.active img",
  carouselPositionIndicatorsCss: "[data-target='#carouselExampleIndicators']",
  laptopsCategoryCss: "[onclick=\"byCat('notebook')\"]",
  linkAboutusCss: "[data-target='#videoModal']",
  linkCarouselLeftArrowClass: ".carousel-control-prev",
  linkCarouselRightArrowClass: ".carousel-control-next",
  linkCartId: "#cartur",
  linkContactCss: "[data-target='#exampleModal']",
  linkHomeCss: "li a[href='index.html']",
  linkLoginId: "#login2",
  linkLogoId: "#nava",
  linkLogoutId: "#logout2",
  linkSignupId: "#signin2",
  linkUserNameId: "#nameofuser",
  monitorsCategoryCss: "[onclick=\"byCat('monitor')\"]",
  nextButtonId: "#next2",
  phonesCategoryCss: "[onclick=\"byCat('phone')\"]",
  previousButtonId: "#prev2",
  productDescriptionsCss: ".card p",
  productImagesCss: ".card > a",
  productPricesCss: ".card div h5",
  productTitlesClass: ".hrefch",
  _lastHomePage: "----------------------------------------------",
  classAddToCartButton : ".btn-success",
  classCards: ".card",
  classCardsTitles: ".card-title a",
  classConfirmButton: ".confirm",
  classProductDescriptionOnCard:".card-text",
  classProductImage : ".product-image",
  classProductPriceOnProd : ".price-container",
  classProductTitle: ".name",
  classProductTitleOnCart: ".name",
  classProductTitleOnProd : ".name",
  classSweetAlert: ".sweet-alert",
  cssCardsBody: "#tbodyid .card",
  cssCardsImage: "#tbodyid .card img.card-img-top",
  cssCardsTitle: "#tbodyid .card .card-title a.hrefch",
  cssCloseOrderModalButton: "#orderModal .btn-secondary[data-dismiss='modal']",
  cssLinkContact : "[data-target='#exampleModal']",
  cssLinkHome : "li a[href='index.html']",
  cssNextButtonEnable: "#next2:not(:disabled)",
  cssPriceNumber: "h5",
  cssPriceOncard: ".card-block h5",
  cssProductDescriptionOnProd: "#more-information p",
  cssProductPriceOnCart: "td:nth-child(3)",
  cssProductRowOnCart: "#tbodyid tr.success",
  cssPurchaseButton: "#orderModal .btn-primary[onclick='purchaseOrder()']",
  cssSweetAlertTitle: ".sweet-alert h2",
  cssTitleOncard: ".card-title a.hrefch",
  idCardInput: "#card",
  idCityInput: "#city",
  idCountryInput: "#country",
  idLinkUserName : "#nameofuser",
  idMonthInput: "#month",
  idNameInput: "#name",
  idNextButton : "#next2",
  idOrderModal: "#orderModal",
  idOrderModalLabel: "#orderModalLabel",
  idPreviousButton : "#prev2",
  idYearInput: "#year",
  selAlertWindow: "window:alert",
  _LoginWindowPagesObject: "---------------",
  idLoginUsername: "#loginusername",
  idLoginPassword: "#loginpassword",
  cssLoginSubmit: "#logInModal .btn.btn-primary",
  _EndOfFile: "----------------------------"
}