module.exports = {
  _firstHomePage: "----------------------------------------------",
  carouselCurrentImageCss: ".carousel-item.active img",
  carouselPositionIndicatorsCss: "[data-target='#carouselExampleIndicators']",
  laptopsCategoryCss: "[onclick=\"byCat('notebook')\"]",
  linkAboutusCss: "[data-target='#videoModal']",
  linkCarouselLeftArrowClass: ".carousel-control-prev",
  linkCarouselRightArrowClass: ".carousel-control-next",
  linkCartId: "#cartur",
  linkContactCss: "[data-target='#exampleModal']",
  linkHomeCss: "li a[href='index.html']",
  linkLoginId: "#login2",
  linkLogoId: "#nava",
  linkLogoutId: "#logout2",
  linkSignupId: "#signin2",
  linkUserNameId: "#nameofuser",
  monitorsCategoryCss: "[onclick=\"byCat('monitor')\"]",
  nextButtonId: "#next2",
  phonesCategoryCss: "[onclick=\"byCat('phone')\"]",
  previousButtonId: "#prev2",
  productDescriptionsCss: ".card p",
  productImagesCss: ".card > a",
  productPricesCss: ".card div h5",
  productTitlesClass: ".hrefch",
  _lastHomePage: "----------------------------------------------",
  _firstSignupWindow: "----------------------------------------------",
  signUserNameInputId: "#sign-username",
  signPasswordInputId: "#sign-password",
  signUpButtonCss: "#signInModal .btn-primary",
  closeButtonCss: "#signInModal .btn-secondary",
  _lastSignupWindow: "----------------------------------------------",
  classAddToCartButton : ".btn-success",
  classCards: ".card",
  classCardsTitles: ".card-title a",
  classConfirmButton: ".confirm",
  classProductDescriptionOnCard:".card-text",
  classProductTitleOnProd : ".name",
  classSweetAlert: ".sweet-alert",
  cssCardsBody: "#tbodyid .card",
  cssCardsImage: "#tbodyid .card img.card-img-top",
  cssCardsTitle: "#tbodyid .card .card-title a.hrefch",
  cssCloseOrderModalButton: "#orderModal .btn-secondary[data-dismiss='modal']",
  cssLinkContact : "[data-target='#exampleModal']",
  cssLinkHome : "li a[href='index.html']",
  cssNextButtonEnable: "#next2:not(:disabled)",
  cssPriceNumber: "h5",
  cssPriceOncard: ".card-block h5",
  cssPurchaseButton: "#orderModal .btn-primary[onclick='purchaseOrder()']",
  cssSweetAlertTitle: ".sweet-alert h2",
  cssTitleOncard: ".card-title a.hrefch",
  idCardInput: "#card",
  idCityInput: "#city",
  idCountryInput: "#country",
  idLinkUserName : "#nameofuser",
  idMonthInput: "#month",
  idNameInput: "#name",
  idNextButton : "#next2",
  idOrderModal: "#orderModal",
  idOrderModalLabel: "#orderModalLabel",
  idPreviousButton : "#prev2",
  idYearInput: "#year",
  selAlertWindow: "window:alert",
  cssPlaceOrderButton: ".btn-success[data-toggle='modal']",
  _CardsPageObject: "---------------",
  cardImagesCss : ".card-img-top.img-fluid",
  cardTitlesCss : ".card-title .hrefch",
  cardPricesCss : ".card-block h5",
  cardDescriptionsCss : ".card-text",
  addToCartButtonClass : ".btn-success",
  _ProductPageObject: "---------------",
  productTitleClass: ".name",
  productPriceOnProdClass : ".price-container",
  productDescriptionOnProdCss: "#more-information p",
  productImageClass : ".product-image",
  _CardsPageObject : "---------------",
  productRowOnCartCss: "#tbodyid tr.success",
  classProductTitleOnCart: ".name",
  cssProductPriceOnCart: "td:nth-child(3)",
  totalPriceId: "#totalp",
  deleteButtonClass: "td:nth-child(4) a",
  placeOrderButtonCss: "button[data-target='#orderModal']",
  _LoginWindowPagesObject: "---------------",
  LoginUsernameId: "#loginusername",
  LoginPasswordId: "#loginpassword",
  LoginSubmitCss: "#logInModal .btn.btn-primary",
<<<<<<< ana
=======
  _ContactWindowPagesObject: "---------------",
  ContactEmailId: "#recipient-email",
  ContactNameId: "#recipient-name",
  MessageTextId: "#message-text",
  ContactSendButtonCss: "#exampleModal .btn.btn-primary",
  ContactCloseButtonCss: "#exampleModal .btn.btn-secondary",
>>>>>>> main
  _EndOfFile: "----------------------------"
}