module.exports = {
  classAddToCartButton : ".btn-success",
  classCards: ".card",
  classCardsTitles: ".card-title a",
  classConfirmButton: ".confirm",
  classLinkCarouselLeftArrow : ".carousel-control-prev",
  classLinkCarouselRightArrow : ".carousel-control-next",
  classProductDescriptionOnCard:".card-text",
  classProductImage : ".product-image",
  classProductImages : ".card > a",
  classProductPriceOnProd : ".price-container",
  classProductTitle: ".name",
  classProductTitleOnCart: ".name",
  classProductTitleOnProd : ".name",
  classProductTitles : ".hrefch",
  classSweetAlert: ".sweet-alert",
  cssCardDescriptions : ".card-text",
  cssCardImages : ".card-img-top.img-fluid",
  cssCardPrices : ".card-block h5",
  cssCardsBody: "#tbodyid .card",
  cssCardsImage: "#tbodyid .card img.card-img-top",
  cssCardsTitle: "#tbodyid .card .card-title a.hrefch",
  cssCardTitles : ".card-title .hrefch",
  cssCarouselImages : ".carousel-item.active img",
  cssCarouselPositionIndicators : "[data-target='#carouselExampleIndicators']",
  cssCloseOrderModalButton: "#orderModal .btn-secondary[data-dismiss='modal']",
  cssLaptopsCategory : "[onclick=\"byCat('notebook')\"]",
  cssLinkAboutus : "[data-target='#videoModal']",
  cssLinkContact : "[data-target='#exampleModal']",
  cssLinkHome : "li a[href='index.html']",
  cssMonitorsCategory : "[onclick=\"byCat('monitor')\"]",
  cssNextButtonEnable: "#next2:not(:disabled)",
  cssPhonesCategory : "[onclick=\"byCat('phone')\"]",
  cssPriceNumber: "h5",
  cssPriceOncard: ".card-block h5",
  cssProductDescriptionOnProd: "#more-information p",
  cssProductPriceOnCart: "td:nth-child(3)",
  cssProductRowOnCart: "#tbodyid tr.success",
  cssPurchaseButton: "#orderModal .btn-primary[onclick='purchaseOrder()']",
  cssSweetAlertTitle: ".sweet-alert h2",
  cssTitleOncard: ".card-title a.hrefch",
  idCardInput: "#card",
  idCityInput: "#city",
  idCountryInput: "#country",
  idLinkCart : "#cartur",
  idLinkLogin : "#login2",
  idLinkLogo : "#nava",
  idLinkLogout : "#logout2",
  idLinkSignup : "#signin2",
  idLinkUserName : "#nameofuser",
  idMonthInput: "#month",
  idNameInput: "#name",
  idNextButton : "#next2",
  idOrderModal: "#orderModal",
  idOrderModalLabel: "#orderModalLabel",
  idPreviousButton : "#prev2",
  idYearInput: "#year",
  selAlertWindow: "window:alert"
}